[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-modes = "0.8.1"
rand = "0.8.4"
aes = "0.7.5"
rsa = "0.5.0"
